### PR TITLE
Fixes to install and run the plugin with Sylius Standard

### LINKED ISSUE #168: Fix installation process on Sylius-Standard

### PR DESCRIPTION
**Pull request by coldic3**
Closes #168, #8

### CODE REVIEW

File: tests/Application/src/Repository/PaymentMethodRepository.php [hunk 1]
```diff
@@ -4,10 +4,11 @@
...
 
-use CommerceWeavers\SyliusTpayPlugin\Repository\FindByChannelWithGatewayConfigTrait;
+use CommerceWeavers\SyliusTpayPlugin\Repository\PaymentMethodTrait;
+use CommerceWeavers\SyliusTpayPlugin\Repository\PaymentMethodRepositoryInterface;
 use Sylius\Bundle\CoreBundle\Doctrine\ORM\PaymentMethodRepository as BasePaymentMethodRepository;
 
 final class PaymentMethodRepository extends BasePaymentMethodRepository implements PaymentMethodRepositoryInterface
 {
-    use FindByChannelWithGatewayConfigTrait;
+    use PaymentMethodTrait;
```
Comment (coldic3) [inline tests/Application/src/Repository/PaymentMethodRepository.php:13]: I think this is a simple and clean approach of naming repository traits. If we want to follow the previous convention, the trait name should be `FindByChannelAndGatewayNameWithGatewayConfigTrait` – that's long, and it's not clear in which repository the trait should be used.

File: src/Tpay/Provider/ValidTpayChannelListProvider.php [hunk 2]
```diff
@@ -4,19 +4,23 @@
...
 use CommerceWeavers\SyliusTpayPlugin\Payum\Exception\UnableToGetBankListException;
+use CommerceWeavers\SyliusTpayPlugin\Repository\PaymentMethodRepositoryInterface;
 use CommerceWeavers\SyliusTpayPlugin\Tpay\PayGroup;
 use CommerceWeavers\SyliusTpayPlugin\Tpay\PaymentType;
 use Payum\Core\Security\CryptedInterface;
 use Payum\Core\Security\CypherInterface;
 use Sylius\Bundle\PayumBundle\Model\GatewayConfigInterface;
 use Sylius\Component\Channel\Context\ChannelContextInterface;
 use Sylius\Component\Core\Model\PaymentMethodInterface;
+use Sylius\Component\Core\Repository\PaymentMethodRepositoryInterface as BasePaymentMethodRepositoryInterface;
```
Comment (lchrusciel) [inline src/Tpay/Provider/ValidTpayChannelListProvider.php:16]: do we need this typhint if `CommerceWeavers\SyliusTpayPlugin\Repository\PaymentMethodRepositoryInterface` already extends it?

**Review by lchrusciel — APPROVED** [review]
